#!/bin/sh
case "$0" in
    /* | [A-Za-z]:/*) hook_path=$0 ;;
    *) hook_path=$PWD/$0 ;;
esac
hook_dir=${hook_path%/*}
exec python "$hook_dir/../scripts/check_commit_attribution.py" --message-file "$1"
